/** WAR — Engine Contract & Capability Manifest. */
import { WORKFLOW_LIFECYCLE_STATES } from "./lifecycle";
import { BUILTIN_WORKFLOW_IDS } from "./builtins";

export const WORKFLOW_RUNTIME_ENGINE_CONTRACT = Object.freeze({
  id: "workflow.runtime",
  name: "Workflow & Automation Runtime",
  version: "1.0.0",
  ownership: {
    owns: [
      "workflow-runtime",
      "workflow-registry",
      "workflow-definitions",
      "workflow-instances",
      "state-machine-execution",
      "scheduling",
      "timers",
      "event-driven-continuation",
      "retry-policies",
      "compensation",
      "checkpointing",
      "execution-history",
      "automation-policies",
      "workflow-governance",
      "workflow-observability",
    ],
    doesNotOwn: [
      "capability-execution",
      "tool-execution",
      "agent-reasoning",
      "presentation",
      "integrations",
      "connectors",
      "railway-capabilities",
      "memory",
      "prompt-runtime",
      "knowledge-graph",
      "journey",
      "decision",
      "trust",
      "goal",
      "spatial",
      "persistence",
      "distributed-scheduling",
      "notifications",
      "payments",
      "authentication",
    ],
  },
  dependencies: {
    frozenEngines: ["agent.runtime", "ctor.runtime", "integration.runtime"],
    ports: [
      "WorkflowCtorPort",
      "WorkflowAgentPort",
      "WorkflowIntegrationPort",
      "WorkflowStatePersistencePort",
    ],
    rule: "WAR reaches other engines exclusively through Agent Runtime, CTOR and IPCF ports (ADR-013/014)",
  },
  lifecycle: WORKFLOW_LIFECYCLE_STATES,
  publishedEvents: [
    "WorkflowCreated",
    "WorkflowRegistered",
    "WorkflowScheduled",
    "WorkflowStarted",
    "WorkflowPaused",
    "WorkflowResumed",
    "WorkflowCompleted",
    "WorkflowCancelled",
    "WorkflowFailed",
    "WorkflowRetried",
    "WorkflowArchived",
    "CheckpointCreated",
    "TimeoutOccurred",
    "CompensationStarted",
    "CompensationCompleted",
    "StepStarted",
    "StepCompleted",
    "StepFailed",
    "StepSkipped",
    "StepWaiting",
    "SignalReceived",
    "TimerFired",
    "ConnectorEvent",
    "AgentEvent",
    "InternalEvent",
    "ScheduledEvent",
  ],
  publicApis: [
    "createWorkflowRuntime",
    "WorkflowRuntime",
    "WorkflowRuntimeFacade",
    "WorkflowManager",
    "WorkflowRegistry",
    "WorkflowFactory",
    "WorkflowStateMachineEngine",
    "Scheduler",
    "TimerManager",
    "CronScheduler",
    "ExecutionQueue",
    "CheckpointManager",
    "SnapshotManager",
    "ExecutionRecovery",
    "TestClock",
    "SystemClock",
    "replayWorkflow",
  ],
  adr: ["ADR-013", "ADR-014", "ADR-015"],
  guarantees: [
    "deterministic-replay",
    "immutable-domain-models",
    "validated-transitions",
    "in-memory-only-state",
    "no-real-cron",
    "no-network-io",
  ],
});

export const WORKFLOW_RUNTIME_CAPABILITY_MANIFEST = Object.freeze({
  id: "workflow.runtime.capability",
  version: "1.0.0",
  category: "automation",
  capabilities: Object.freeze([
    { id: "workflow.register", description: "Register an immutable workflow definition" },
    { id: "workflow.create", description: "Create a workflow instance" },
    { id: "workflow.start", description: "Execute a workflow instance deterministically" },
    { id: "workflow.pause", description: "Pause a running workflow" },
    { id: "workflow.resume", description: "Resume a paused workflow" },
    { id: "workflow.cancel", description: "Cancel a workflow instance" },
    { id: "workflow.signal", description: "Deliver an event/signal to a waiting workflow" },
    { id: "workflow.schedule", description: "Schedule delayed, recurring or cron execution" },
    { id: "workflow.timer", description: "Fire a due workflow timer" },
    { id: "workflow.checkpoint", description: "Create a workflow checkpoint" },
    { id: "workflow.snapshot", description: "Capture a workflow snapshot" },
    { id: "workflow.recover", description: "Recover execution from the latest checkpoint" },
    { id: "workflow.replay", description: "Deterministically replay workflow history" },
    { id: "workflow.statistics", description: "Report workflow statistics" },
    { id: "workflow.health", description: "Report workflow runtime health" },
  ]),
  builtinWorkflows: BUILTIN_WORKFLOW_IDS,
  observability: Object.freeze([
    "workflow-metrics",
    "execution-metrics",
    "scheduler-metrics",
    "retry-metrics",
    "checkpoint-metrics",
    "latency-metrics",
    "tracing",
    "structured-logging",
    "health-checks",
  ]),
});
